### ISSUE TITLE
Multiple side-informations per macau-prior

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#100]
- one lambda value per side information
- side-info matrices are concatenated
- only for dense or sparse with `--direct`
- also specify --direct per side-info

In the ini-file, move these 
```
# for macau priors
lambda_beta = 10
tol = 1e-06
direct = 0
```
from `[global]` to per `[side_info_x]`

**Comment by motoharu-yano** [comment]
I have implemented everything in issue-100 branch, including ISideInfo interface.
Now MacauPrior and MacauOnePrior are not template classes anymore.
They can store multiple side information matrices of different type (Dense, Sparse, Scarse).

**Comment by motoharu-yano** [comment]
Everything was merged to master branch. 
Command line arguments, ini files, macau priors should have the ability to support multiple side informations now. However they still use only one side information at the moment.
The only thing that is left to implement is internal functionality of MacauPrior and MacauOnePrior.
This is still an open question since we need to discuss multiple details of implementation including:
- how we will handle multiple side info matrices in update_prior producing Uhat matrices.
- how are we going to combine multiple Uhat matrices into a single result matrix.

I have named only few issues that I know. Feel free to update the list.
