### ISSUE TITLE
Fix Wishart for dim == 1

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#14]
Port b9cf1d8fa from master to smurff.

**Comment by ipasechnikov** [comment]
All new Wishart changes from macau `master` branch are now in `master-smurff-merge` branch. 9f7ea316f8a42ed56d4f48527345a282fad3232e - here Wishart is up to date with macau.

Also there are new targets in [linux/Makefile](https://github.com/ExaScience/smurff/blob/master-smurff-merge/lib/smurff-cpp/makefiles/linux/Makefile): `bench_nrandn`, `bench_wishart` and `bench_mvnormal`.
Wishart results were compared with macau `master` that was temporary modified so that it had same random generation as `smurff`. Results were the same for macau `master` and smurff `master-smurff-merge` branches.

So I suppose we can close this issue.
