### ISSUE TITLE
Missing virtual destructors

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#25]
from @motoharu-yano :

> While looking in the code I have noticed other potential issue. It looks like we are missing virtual destructors in different interfaces.

> [... W]e have found out that smart pointers like unique_ptr don't warn you about virtual destructors. That's how it is. But we can use -Wnon-virtual-dtor compiler flag that works both for gcc and clang

**Comment by ipasechnikov** [comment]
I suppose this issue can be closed. It was fixed in 83ac6ee51bba29007a7f4d9359a8d019d9a99d9d commit.
Now we have a `-Wnon-virtual-dtor` gcc/clang compiler flag in [`Makefile.common`](https://github.com/ExaScience/smurff/blob/83ac6ee51bba29007a7f4d9359a8d019d9a99d9d/lib/smurff-cpp/Makefile.common#L3), that displays warnings in case we have a missing virtual constructor.
