### ISSUE TITLE
Enable tensor functionality for Y

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#6]
- Existing functionality in "jaak-s/macau" transfer into "ExaScience/smurff"
   - Unit test containing the word "tensor"
   - integration tests containing the word tensor
      - test_bpmf_tensor (LOC114)
      - test_bpmf_tensor2 (LOC143)
      - test_bpmf_tensor3 (LOC148)
      - test_macau_tensor (LOC171)
      - test_macau_tensor_univariate (LOC191)
      - test_macau_tensor_empty (LOC209)
  - Some code snippets do exist in "ExaScience/smurff"
  - TODO: Tom, please clarify

**Comment by tvandera** [comment]
## Support for tensor input into SMURFF:

config.h:
- [ ] Generalize MatrixConfig to support tensors (dense+sparse)
matrix_io.h:
- [ ] Add support for reading and writing *text* tensor data in files (.csv format?)
- [ ] Add support for reading and writing *binary* tensor data in files (.ddt and .sdt formats?)

## internal Sparse and Dense representation 
data.h:
- [ ] Put DenseTensorData, SparseTensorData, etc in Data class hierarchy
- [ ] TensorsData (like MatricesData)

## Adapt other classes to support nmode > 2
- [ ]  Result class
- [ ]  Model class 
- [ ] Other?

## Priors
- [ ] Update ILatentPrior::sample_latent

**Comment by tvandera** [comment]
Have a look at
`virtual void setTrain(int idx, int nmodes, double values, int nnz, int* dims) = 0;`
in `sparsetensor.h`
to get an idea on how to pass tensor data into smurff
the parameters of `setTrain` should be in `TensorConfig`
like the parameters of
`virtual void setTrain(int rows, int cols, double* values, int nnz, int nrows, int ncols) = 0;`
are the main parts of `MatrixConfig`

**Comment by motoharu-yano** [comment]
Here is my summary on the pieces of code that have to be handled.

PRIORS:

- GlobalPrior.cpp
-- sample_latent specific for tensor (sample_latent_tensor). old code is added.

- MacauOnePrior.cpp
-- tensor sample_latents. old code is added.
-- tensor sample_latents probit specific. old code is added.

- MacauPrior.cpp
-- tensor sample_latents. old code is added.
-- tensor sample_latents probit specific. old code is added.

- NormalPrior.cpp
-- tensor sample_latents. old code is added.
-- tensor sample_latents probit specific. old code is added.

EVAL:

- data.cpp
-- var_total for tensor. old code is added.
-- sumsq for tensor. old code is added.

- result.cpp
-- eval_rmse_tensor specific to tensor. old code is added.

CONFIGS:

- MatrixConfig.cpp
-- first wave of refactoring and adopting tensors is done.

- TensorConfig.cpp
-- first wave of refactoring and adopting tensors is done.

OTHER:

- sparsetensor.cpp
-- this is completely new and was added as is currently.

**Comment by ipasechnikov** [comment]
> Generalize MatrixConfig to support tensors (dense+sparse)

All these changes were done in 4af205cf442621f9eca0efc64a995c53e3bd8158 commit.
- Added [`TensorConfig` ](https://github.com/ExaScience/smurff/blob/master-smurff-merge/lib/smurff-cpp/TensorConfig.h) class. It is a base class for `MatrixConfig`. So from now on matrix is considered to be a tensor.
- [`MatrixConfig`](https://github.com/ExaScience/smurff/blob/master-smurff-merge/lib/smurff-cpp/MatrixConfig.h) is fully refactored now. There are still left raw pointer constructors. We will gradually remove them as we move to `std::shared_ptr` and `std::vector`. Or leave them to provide compatibility but add new constructors that work with `std::shared_ptr` and `std::vector`.
- `TensorConfig` and `MatrixConfig` use getters and setters now. So that you cannot directly access their fields. And for sure there are no raw pointers available. From now on you work with `std::vector`.
- [`NoiseConfig`](https://github.com/ExaScience/smurff/blob/master-smurff-merge/lib/smurff-cpp/NoiseConfig.h) is now moved to new separate files.
- Almost all `matrix_io` methods can now use general `std::istream` and `std::ostream` to read to and write from.
- Also there are tons of tests added to [`tests.cpp`](https://github.com/ExaScience/smurff/blob/master-smurff-merge/lib/smurff-cpp/tests.cpp) for `matrix_io` methods, `gen_random/extract` function, `MatrixConfig` and `TensorConfig` constructors.
---
There are still some things left to be done.
- Make sure that there are no memory leakages, no extra memory allocations and other memory related problems like rows/cols caching for `MatrixConfig`.
- Provide new constructors to `TensorConfig` and `MatrixConfig`  that work with `std::shared_ptr` and `std::vector`.
- Add some more tests for `matrix_io` functions that work with filename.

And also we are left with two more tasks. I suppose we will consider them a bit later. I actually don't know if there are any tensor file examples and formats available. If there are any, could you please provide them?
> Add support for reading and writing text tensor data in files (.csv format?)
> Add support for reading and writing binary tensor data in files (.ddt and .sdt formats?)
---
For now everything is merged into `master-smurff-merge`, compiles and all tests pass. Except for [this one](https://github.com/ExaScience/smurff/blob/master-smurff-merge/lib/smurff-cpp/tests.cpp#L951) cause it requires a matrix file. You can make it pass if you place a matrix file next to `tests` executable.'

064842fcd1199140f56d444ec9dea982b10b08a2 - latest available commit that you can use to check out all these changes.

Feel free to review, comment and make suggestions.

**Comment by ipasechnikov** [comment]
In the latest for now commit 4bac09af826015679e25bf97704562293ca224bf we have removed old `MatrixConfig` and `TensorConfig` constructors that use raw pointers. Now you create `MatrixConfig` and `TensorConfig` instances from `std::vector` or `std::shared_ptr`.

https://github.com/ExaScience/smurff/blob/4bac09af826015679e25bf97704562293ca224bf/lib/smurff-cpp/MatrixConfig.h#L18-L52

https://github.com/ExaScience/smurff/blob/4bac09af826015679e25bf97704562293ca224bf/lib/smurff-cpp/TensorConfig.h#L30-L41

- `std::vector` version constructors copy all the data. So there can be considered as the safest. No memory leaks, no shared memory, nothing. 
- `std::shared_ptr` version can be used to gain extra performance cause it doesn't copy values from `std::vectors` It just saves the pointer, no data is copied. But you should be extra careful, because this data can be shared, so somewhere else it can be changed. But if you are totally sure and know what you are doing then it's fine.

There are also two types of getters for `MatrixConfig` and `TensorConfig`.

https://github.com/ExaScience/smurff/blob/4bac09af826015679e25bf97704562293ca224bf/lib/smurff-cpp/TensorConfig.h#L56-L62

https://github.com/ExaScience/smurff/blob/4bac09af826015679e25bf97704562293ca224bf/lib/smurff-cpp/MatrixConfig.h#L61-L65

- One of the getters returns `const std::vector&`. So no data is copied unless you try to save it into another `std::vector` variable. So you can use this getter most of the time, to iterate over rows or 
- The other one returns `std::shared_ptr`. Same thing must be considered as for constructor. You should know exactly what you are doing.

Also as you can see, all fields like `nnz`, `nmodes`, are now of type `size_t` instead of `int`. That was done to ensure that they are never less than zero and can have the max value possible depending on machine architecture.
https://github.com/ExaScience/smurff/blob/4bac09af826015679e25bf97704562293ca224bf/lib/smurff-cpp/TensorConfig.h#L20-L21

**Comment by ipasechnikov** [comment]
There are new `TensorConfig` and `MatrixConfig` constructors available that use rvalue references to improve performance. These constructors don't copy `std::vector` values, but instead they move them.

https://github.com/ExaScience/smurff/blob/8095a78654c7cf2689948d892caf247ba2dd111b/lib/smurff-cpp/MatrixConfig.h#L28-L32

https://github.com/ExaScience/smurff/blob/8095a78654c7cf2689948d892caf247ba2dd111b/lib/smurff-cpp/MatrixConfig.h#L52-L58

https://github.com/ExaScience/smurff/blob/8095a78654c7cf2689948d892caf247ba2dd111b/lib/smurff-cpp/MatrixConfig.h#L79-L84

https://github.com/ExaScience/smurff/blob/8095a78654c7cf2689948d892caf247ba2dd111b/lib/smurff-cpp/MatrixConfig.h#L104-L109

You can find use examples in `matrix_io.cpp`. Return statement below creates `MatrixConfig` with moved `std::vector`. It's safe to move its value here because this `std::vector` is a temporary value and not used anywhere else after move.
https://github.com/ExaScience/smurff/blob/8095a78654c7cf2689948d892caf247ba2dd111b/lib/smurff-cpp/matrix_io.cpp#L540-L552

**Comment by motoharu-yano** [comment]
Matrix i/o and Tensor i/o is now implemented for binary files and text files.
However during last meeting we have discussed that more txt formats exist and probably need support.
This includes MM formats: dense, pattern.

**Comment by motoharu-yano** [comment]
SparseMode and TensorData classes are implemented.
Currently TensorData represents a scarce tensor.

TensorData class can be created through TensorDataFactory class.

TensorData class is created from TensorConfig which can be read with tensor_io functions (including txt and binary data).

TensorConfig is integrated into CmdSession and Config class so that train and test data can be represented as tensors.

TensorData class now fully implements Data interface.

Most important functions for priors are: get_pnm, update_pnm. In theory there should be no problem using TensorData with any prior.

Other important functions are var_total, sumsq and train_rmse which are also implemented.
Model and Submodel classes was adjusted to allow tensors. 4 new iterators for V matrices were introduced:
- VMatrixExprIterator
- ConstVMatrixExprIterator
- VMatrixIterator
- ConstVMatrixIterator

Result class was adjusted to allow tensors. This mostly includes set and update methods.

**Comment by tvandera** [comment]
Moved still-open issues to #68, #69, #70, #71
