### ISSUE TITLE
Move ini utils into INIReader class

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#96]
low priority

**Comment by motoharu-yano** [comment]
I have partially implemented this. We now have INIFile instead of INIReader. Utils are removed.
I have adjusted some usages of this class and tested save/restore functionality.
Fixed couple of bugs with checkpointing on the way.

There are still some places that can be cleaned up (marked with bold):

Config
  save - **uses old code without ini file class**
  restore - uses INIFile

RootFile
  save - uses INIFile
  restore - uses INIFile
  
StepFile
  save - burning and sampling uses INIFile
  restore - uses INIFile

result
  save - **uses old code without ini file class**
  restore - uses INIFile
  
TensorConfig
  save - **uses old code without ini file class**
  restore - uses INIFile

**Comment by motoharu-yano** [comment]
All the classes are fixed now. The use INIFile properly.
