### ISSUE TITLE
reading and writing csv files from matrix_io package does not work

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#98]

**Comment by tvandera** [comment]
Fixed in 80aba7f51935c6a73bb1cd18a50f6f69d55bed96
@ipasechnikov can you test?

**Comment by ipasechnikov** [comment]
Updated [test_matrix_io.py](https://github.com/ExaScience/smurff/blob/705f1cfcb06f49d29aff683796b74b3a9531bbc4/python/matrix_io/test/test_matrix_io.py) tests in commit 705f1cfcb06f49d29aff683796b74b3a9531bbc4. They all pass.

**Comment by tvandera** [comment]
x-check with files generated by smurff C++ code

**Comment by ipasechnikov** [comment]
Added test case to [`TestsMatrixIO.cpp`](https://github.com/ExaScience/smurff/blob/fceac80fd96393691b8ed0a503ce2dc8145ba906/lib/smurff-cpp/Tests/TestsMatrixIO.cpp#L795) to generate different types of matrices that are used in new [`test_matrix_io.py`](https://github.com/ExaScience/smurff/blob/d90fd1d2e591d0567bcd9e9e15c8d5c588f598ac/python/matrix_io/test/test_matrix_io.py#L136) tests.

By default this `TestsMatrixIO.cpp` test case has `[!hide]` flag set. So that it is skipped when you run tests. But there are already pre-generated matrices in [`python/matrix_io/test/test_data`](https://github.com/ExaScience/smurff/tree/d90fd1d2e591d0567bcd9e9e15c8d5c588f598ac/python/matrix_io/test/test_data) directory for `test_matrix_io.py` to use.
